### ISSUE TITLE
User Story : Early Heroku Deployment

### ISSUE THREAD

**Issue by YesCoops** [YesCoops/Wavey#10]
As a **Developer** I want to **deploy to Heroku early** so that **I can check everything is working correctly before developing the Site**

## Tasks
- [x] Create a new Heroku App
- [x] Add the database to the app resources
- [x] Add the secret key’s to the Heroku config vars
- [x] Configure the settings.py file to look at env.py, the os in deployment and correct database url from Heroku. 
- [x] Add cloudinary API to env.py and Heroku config vars
- [x] Adjust the settings.py file to look at the required Cloudinary libraries
