### ISSUE TITLE
User Story : Django Secret keys

### ISSUE THREAD

**Issue by YesCoops** [YesCoops/Wavey#11]
As a **Developer** I can **store the development secret keys in Django** so that **no sensitive data is compromised**

## Tasks

- [x] Create an env.py file to store the environment variables needed such as the api keys and DB secret keys
- [x] Update Django to point to the new locations for the secret keys
- [x] Add the env.py file to the .gitignore file so that it does not get pushed to GitHub
