### ISSUE TITLE
User Story : Create a User Account

### ISSUE THREAD

**Issue by YesCoops** [YesCoops/Wavey#13]
As a **User** I can **create an account** so that **I can create, save and like posts**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am an unregistered User
	**When** I access the Site
	**Then** I can register as a User

- Acceptance Criteria 2
	**Given** that I am an unregistered User
	**When** I am on the user registration page and input a valid Username, email address and password
	**Then** the system creates me an account

- Acceptance Criteria 3
	**Given** that I am a registered User
	**When** I am logged into my account
	**Then** I can create my own post and see what posts I have saved

- Acceptance Criteria 4
	**Given** that I am a registered User
	**When** I have logged into my account
	**Then** I can no longer see the register button

## Tasks
- [x] Develop a way for a user to create an account
- [x] Develop a button in the NavBar/Call to Action that takes them to registration page
- [x] Create user registration form
- [x] Remove register button once user is signed in
- [x] Once registered/singed in, show button to create post which takes user to create post page.
