### ISSUE TITLE
User Story: Comment on a post

### ISSUE THREAD

**Issue by YesCoops** [YesCoops/Wavey#21]
As a **User** I can **comment on a post** so that **I can contact the author**

## Acceptance Criteria

- Acceptance Criteria 1
	**Given** that I am a registered User
	**When** I am in the post detail view
	**Then** I can see the comment box
- Acceptance Criteria 2
	**Given** that I am a registered User
	**When** I add text to the comment box
	**Then** I can add a comment to that post

## Tasks
- [ ] Create comment section in post detail page
- [ ] Allow box to be visible only to registered Users
- [ ] Develop comment posting 
- [ ] Show list of comments to registered Users only
