### ISSUE TITLE
User Story: Like a Post

### ISSUE THREAD

**Issue by YesCoops** [YesCoops/Wavey#22]
As a **User** I can **like a post** so that **I can notify the author that I like their content**

## Acceptance Criteria

- Acceptance Criteria 1
	**Given** that I am a registered User
	**When** I look at another post
	**Then** I can see the like button
- Acceptance Criteria 2
	**Given** that I am a registered User
	**When** I click on the like button
	**Then** a like is added to the overall count on the post
- Acceptance Criteria 3
	**Given** that I am an unregistered User 
	**When** I access a post
	**Then** I cannot click the like button
- Acceptance Criteria 4
	**Given** that
	**When** the
	**Then**

## Tasks
- [x] Develop a like button in the post detail view
- [x] Make the button visible to registered users
- [x] Make the button hidden/inactive for unregistered Users
- [x] Develop a method to count the like when the button is clicked (and remove the count when unchecked)
